### PR TITLE
feat: adjust async router types

### LINKED ISSUE #28: wrong AsyncRouter types
`getAsync` use `IRouterMatcher` that doesn't allow return promise from handler:

```ts
router.getAsync('/user', async (req, res) => {
   
})
```

```
Promise returned in function argument where a void return was expected  @typescript-eslint/no-misused-promises
```

the same problem as in #25

### PR DESCRIPTION
**Pull request by Drapegnik**
fixes #28

### CODE REVIEW

**Comment by Aankhen** [comment]
Looks pretty good to me (with the caveat that this would now need to be kept in sync with the upstream types).

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
I really don't like the extra unnecessary dependency. Why not just do something like `useAsync: IRouter['use'] | (req?: Request, res?: Response, next?: Function) => Promise<void>` ?

**Comment by Drapegnik** [comment]
@vkarpov15, `@types/express-serve-static-core` is used by [`@types/express`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/package.json#L4), so anyone who use express + ts would already have this package

I added it as peer deps, so it's optional

**Comment by Drapegnik** [comment]
`| (req?: Request, res?: Response, next?: Function) => Promise<void>` doesn't looks like right type here (too simple)

**Comment by vkarpov15** [comment]
"too simple" is likely why it's the right choice :) I'm going to close this PR, way too complex.

**Comment by Drapegnik** [comment]
@vkarpov15, by "too simple" I mean that it doesn't cover all cases, so would lead to ts errors

**Comment by zone117x** [comment]
Fixing these types are necessarily going to be complex. The couple possible approaches are either:

A) Highly inscrutable recursive argument extraction to convert types like `IRouter['get']` into a proper async function, or
B) Manually re-defining the nested types in order to recreate a proper async version of types like `IRouter['get']` -- which is what this PR attempted.

@vkarpov15 I think this PR or something similar should be re-considered. We're running into significant eslint issues because of this, and if you aren't open to a PR like this, then we (and likely others) are going to move away from using this lib.

**Pull request closed without merging**
